### PR TITLE
Support debug portfile

### PR DESCRIPTION
**Pull request by JackBoosY**

### CODE REVIEW

**Comment by JackBoosY** [comment]
Upload plugin to test.
[vcpkg-cmake-tools-2.1.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14370003/vcpkg-cmake-tools-2.1.0.vsix.zip)

**Comment by JackBoosY** [comment]
@FrankXie05  please test this first.

**Comment by FrankXie05** [comment]
@JackBoosY Do I need to manually package and generate new extensions? (I don’t have the local environment to integrate it :( )

**Comment by JackBoosY** [comment]
> Upload plugin to test. [vcpkg-cmake-tools-2.1.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14370003/vcpkg-cmake-tools-2.1.0.vsix.zip)

@FrankXie05 download this manually, unzip, and manually install into VSCode.

**Comment by FrankXie05** [comment]
@JackBoosY Yes, It has been tested locally and everything is normal for the debug vcpkg portfile.cmake. But it does not return PipName: `\\\\.\\pipe\\vcpkg_ext_portfile_dbg`, causing this to be added manually.

**Comment by JackBoosY** [comment]
> @JackBoosY Yes, It has been tested locally and everything is normal for the debug vcpkg portfile.cmake. But it does not return PipName: `\\\\.\\pipe\\vcpkg_ext_portfile_dbg`, causing this to be added manually.

Did you mean `\\\\.\\pipe\\vcpkg_ext_portfile_dbg` was not added automatically to `Tasks.json` or `Launch.json`?

**Comment by FrankXie05** [comment]
> > @JackBoosY Yes, It has been tested locally and everything is normal for the debug vcpkg portfile.cmake. But it does not return PipName: `\\\\.\\pipe\\vcpkg_ext_portfile_dbg`, causing this to be added manually.
> 
> Did you mean `\\\\.\\pipe\\vcpkg_ext_portfile_dbg` was not added automatically to `Tasks.json` or `Launch.json`?

Yes, it needs to be added manually. It seems that it is cleaned up every time after debugging and does not return.

**Comment by JackBoosY** [comment]
@FrankXie05 Please repro this issue and get the log in `OUTPUT` - `vcpkg` channel then provide it.

**Comment by FrankXie05** [comment]
@JackBoosY Ok, I will upload the video of the reproduction and the operation.

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.1.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14405966/vcpkg-cmake-tools-2.1.0.vsix.zip)
@FrankXie05 Try this.

**Pull request merged**
