### PR TITLE
Support debug port's CMakeLists

### PR DESCRIPTION
**Pull request by JackBoosY**

### CODE REVIEW

**Comment by FrankXie05** [comment]
When will a new `vsix` be released?(after merged this pr? 🫡)

**Comment by JackBoosY** [comment]
> When will a new `vsix` be released?(after merged this pr? 🫡)

After you test https://github.com/JackBoosY/vcpkg-vscode-extension/pull/9 pass.

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14413992/vcpkg-cmake-tools-2.2.0.vsix.zip)
@FrankXie05 Try this. Please note that debug CMakeLists only support `--editable` mode since rebuild port will delete the port's source folder, which also will delete the breakpoint.

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14414328/vcpkg-cmake-tools-2.2.0.vsix.zip)
Try this.

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14415910/vcpkg-cmake-tools-2.2.0.vsix.zip)

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14415980/vcpkg-cmake-tools-2.2.0.vsix.zip)

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14416127/vcpkg-cmake-tools-2.2.0.vsix.zip)

**Comment by JackBoosY** [comment]
[vcpkg-cmake-tools-2.2.0.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14418663/vcpkg-cmake-tools-2.2.0.vsix.zip)

**Pull request merged**
